version: '3.8'

services:
  app:
    container_name: farmpigs-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@farmpigs-postgres:5432/farmpigs?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: supersecret
    depends_on:
      - postgres
    networks:
      - farmpigs-network

  postgres:
    image: postgres:15-alpine
    container_name: farmpigs-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farmpigs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmpigs-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: farmpigs-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - farmpigs-network

networks:
  farmpigs-network:
    driver: bridge

volumes:
  postgres_data: